### ISSUE TITLE
can you play rtmp in chrome ?

### ISSUE THREAD

**Issue by ch-zgh-1993** [savokiss/vue-videojs-demo#1]
can you play rtmp in chrome ? or you have some idea about play rtmp stream in chrome.
thank you .

**Comment by savokiss** [comment]
Of course. RTMP needs Adobe Flash plugin && videojs-flash.js. Please see the online demo.

**Comment by ch-zgh-1993** [comment]
but it not work! my chrome version is the lastest.

**Comment by savokiss** [comment]
No more activities, closing.
