### ISSUE TITLE
怎么循环渲染src呢

### ISSUE THREAD

**Issue by alexyuetmout** [savokiss/vue-videojs-demo#3]
有一个需求,页面同时有好多个播放器,但是src不是死的.要动态获取.获取到之后要怎么循环赋值进去么. 有办法讲src放在组件属性么

**Comment by savokiss** [comment]
可以的呀，这些都是 vue 层面的知识
修改 src 的话 代码里面已经有了，直接修改 playerOptions 的属性就可以了
```js
      this.playerOptions.sources[1].src = this.streams.hls
      this.playerOptions.sources[0].src = this.streams.rtmp
```

将 src 放到组件属性的话，你可以 watch 这个组件属性，然后再修改到 playerOptions 中就行了
