### ISSUE TITLE
直播引入 rtmp 报错

### ISSUE THREAD

**Issue by wangyano0** [savokiss/vue-videojs-demo#4]
楼主你好，我想问一下 ：我已经安装了 videojs-flash  并且引入了。可是为什么还是会报错呢，应该怎么解决呢
![image](https://user-images.githubusercontent.com/11673604/40964862-c12d9bc6-68de-11e8-90c6-3f38d125f1d3.png)
![image](https://user-images.githubusercontent.com/11673604/40964887-d553788c-68de-11e8-8bc8-6b99e9cb47f6.png)
![image](https://user-images.githubusercontent.com/11673604/40964903-e0a1b398-68de-11e8-9e68-08ff078717b2.png)

**Comment by savokiss** [comment]
你可以参考我项目里的代码，我是在 `main.js` 中引入的
