### ISSUE TITLE
在electron-vue项目播放rtmp出现无法使用flash技术

### ISSUE THREAD

**Issue by wallowbear** [savokiss/vue-videojs-demo#5]
E:\work\test\electron\test\node_modules\_video.js@6.12.0@video.js\dist\video.cjs.js:450 VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.

E:\work\test\electron\test\node_modules\_video.js@6.12.0@video.js\dist\video.cjs.js:450 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."

但我看你测试网页上是可以播放的 https://surmon-china.github.io/vue-video-player/，我等下不用electron再试一下

**Comment by savokiss** [comment]
electron 中本身需要单独启用 flash
这个问题可以参考：<https://github.com/videojs/video.js/issues/4273>
