### ISSUE TITLE
为什么clone的项目在本地运行之后没法播放rtmp呢？

### ISSUE THREAD

**Issue by cn-Meepo** [savokiss/vue-videojs-demo#6]
请问下为什么clone的项目在本地运行之后没法播放rtmp呢？你提供的demo是可以播放的，放到自己本地就不行了

**Comment by savokiss** [comment]
是由于版本不一致导致的，你可以把依赖版本强制锁定为本项目的版本。目前最新版本 播放rtmp 有问题，暂时没有调通

**Comment by Jermyo** [comment]
那个依赖的版本？我是根据你package.json 里的版本安装的依赖，为什么还是不行呢

**Comment by savokiss** [comment]
链接有么？我本地跑这个链接是可以的：rtmp://184.72.239.149/vod/&mp4:BigBuckBunny_115k.mov

**Comment by EndyCan** [comment]
发现移动端播放不了

**Comment by EndyCan** [comment]
播放不了rtmp视频，报 ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.  pc正常

**Comment by Jermyo** [comment]
> 播放不了rtmp视频，报 ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. pc正常

移动端api自动屏蔽掉了自动播放，你看IOS的就没问题，小米华为自动屏蔽掉了，解决办法我找了半天也没找到，你要是有什么好的解决办法记得共享一下，谢谢

**Comment by gdoudeng** [comment]
+1！！！移动端播放不了rtmp！包括这个demo！求救！
